# Railway deployment configuration
# This file should be placed in the root of your Backend folder

# Build Command
build = "mvn clean package -DskipTests"

# Start Command
start = "java -jar target/*.jar"

# Environment Variables for Railway
# Set these in your Railway dashboard or use the Railway CLI:
# railway variables set SPRING_DATASOURCE_URL="mysql://root:CukuutGHHsftrjFYLabrdadFEjnaJUdT@mysql.railway.internal:3306/railway"
# railway variables set SPRING_DATASOURCE_USERNAME="root"
# railway variables set SPRING_DATASOURCE_PASSWORD="CukuutGHHsftrjFYLabrdadFEjnaJUdT"
# railway variables set CORS_ALLOWED_ORIGINS="https://your-frontend-app.railway.app"
# railway variables set SPRING_JPA_SHOW_SQL="false"

[build]
  command = "mvn clean package -DskipTests"

[deploy]
  startCommand = "java -jar target/*.jar"